# Generated by Mio Manual Input
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTesterhome:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.driver.get("https://testerhome.com/")
        self.driver.implicitly_wait(5)

    def teardown_method(self):
        self.driver.quit()

    def test_testerhome(self):
        self.driver.find_element(By.LINK_TEXT, '社团').click()
        self.driver.find_element(By.CSS_SELECTOR, '[data-name="霍格沃兹测试学院"]').click()
        self.driver.find_element(By.CSS_SELECTOR, '.topic:nth-child(1) .title>a').click()
